name: Jakal
favicon: null
layout_spectrum: 0.935121514601633
typography_spectrum: 0.6867236408870667
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7282243771478534
  lightness: 0.7810159295331687
  saturation: 0.5231094050686806
  rhythmicContrast: 0.8570838423911482
purpose: []
